# Generated by Django 5.2.3 on 2025-06-21 08:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioInstruction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_file', models.FileField(upload_to='audio_wills/')),
                ('testator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_instructions', to='authentication.userprofile')),
            ],
            options={
                'verbose_name': 'AudioInstruction',
                'verbose_name_plural': 'AudioInstruction',
            },
        ),
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('testator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='executor', to='authentication.userprofile')),
            ],
            options={
                'verbose_name': 'Executor',
                'verbose_name_plural': 'Executors',
            },
        ),
        migrations.CreateModel(
            name='Heir',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('testator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heirs', to='authentication.userprofile')),
            ],
            options={
                'verbose_name': 'Heir',
                'verbose_name_plural': 'Heirs',
            },
        ),
        migrations.CreateModel(
            name='ConfidentialInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_type', models.CharField(max_length=100)),
                ('email_or_username', models.CharField(max_length=255)),
                ('instructions', models.TextField()),
                ('testator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confidential_infos', to='authentication.userprofile')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confidential_access', to='administration.heir')),
            ],
            options={
                'verbose_name': 'ConfidentialInfo',
                'verbose_name_plural': 'ConfidentialInfo',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('testator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='authentication.userprofile')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inherited_assets', to='administration.heir')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
        migrations.CreateModel(
            name='PostDeathInstruction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instructions', models.TextField()),
                ('testator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_death_instruction', to='authentication.userprofile')),
            ],
            options={
                'verbose_name': 'PostDeathInstruction',
                'verbose_name_plural': 'PostDeathInstructions',
            },
        ),
        migrations.CreateModel(
            name='SpecialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_type', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=255)),
                ('platform_or_location', models.CharField(max_length=255)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_accounts', to='administration.heir')),
                ('testator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_accounts', to='authentication.userprofile')),
            ],
            options={
                'verbose_name': 'SpecialAccount',
                'verbose_name_plural': 'SpecialAccounts',
            },
        ),
    ]
