# Generated by Django 5.2.3 on 2025-06-21 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_asset_created_at_asset_updated_at_and_more'),
        ('authentication', '0004_alter_userprofile_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialaccount',
            name='platform_or_location',
        ),
        migrations.AddField(
            model_name='specialaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='specialaccount',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='specialaccount',
            name='account_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specialaccount',
            name='testator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_accounts', to='authentication.userprofile'),
        ),
    ]
