# Generated by Django 5.2.3 on 2025-06-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_remove_specialaccount_platform_or_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confidentialinfo',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='confidentialinfo',
            name='email_or_username',
        ),
        migrations.AddField(
            model_name='confidentialinfo',
            name='confidential_file',
            field=models.FileField(blank=True, null=True, upload_to='confidential_files/'),
        ),
    ]
