# Generated by Django 5.2.3 on 2025-06-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_remove_asset_assigned_to_asset_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_image',
            field=models.ImageField(blank=True, null=True, upload_to='asset_images/'),
        ),
        migrations.AddField(
            model_name='asset',
            name='instruction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
