# Generated by Django 5.2.3 on 2025-06-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_alter_asset_asset_type_alter_asset_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heir',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='heir',
            name='relationship',
            field=models.CharField(choices=[('Spouse', 'Spouse'), ('Child', 'Child'), ('Parent', 'Parent'), ('Sibling', 'Sibling'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
