# Generated by Django 5.2.3 on 2025-06-24 10:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_alter_heir_full_name_alter_heir_relationship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confidentialinfo',
            name='assigned_to',
        ),
        migrations.CreateModel(
            name='SpecialAccountDeleteToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('special_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.specialaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='confidentialinfo',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='confidential_access', to='administration.heir'),
        ),
    ]
