# Generated by Django 5.2.3 on 2025-06-24 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_pendingconfidentialinfoupdate'),
        ('authentication', '0006_pendinguserprofileupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingHeirVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('testator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
            ],
        ),
    ]
