# Generated by Django 5.2.3 on 2025-06-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_pendingheirverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heir',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
