# Generated by Django 5.2.3 on 2025-06-29 18:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_alter_heir_date_of_birth'),
        ('authentication', '0008_userprofile_manageuseraccount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingAssetVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('testator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
            ],
        ),
    ]
