# Generated by Django 5.2.3 on 2025-07-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0014_pendingaudioupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='inherited_assets', to='administration.heir'),
        ),
        migrations.AlterField(
            model_name='confidentialinfo',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='confidential_access', to='administration.heir'),
        ),
    ]
