# Generated by Django 5.2.3 on 2025-06-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('---------', '---------'), ('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20, null=True),
        ),
    ]
