# Generated by Django 5.2.3 on 2025-06-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='roles',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Testator', 'Testator')], default='Testator', max_length=255, null=True),
        ),
    ]
